name: A workflow for my hello world file
on: push

jobs:
  NameOf1stJob:
    name: this is 1st job name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Brian Le"
  secondJob:
    name: this is 2nd job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Edna Tran"